version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pokedex-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pokedexdb
      MYSQL_USER: mjvini
      MYSQL_PASSWORD: Euamopokemon1
      MYSQL_ROOT_PASSWORD: Euamopokemon2
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
